CREATE EXTERNAL TABLE IF NOT EXISTS OBJECTIVE_AERODROMO.ICAO_NAME_LIST (
    icao STRING,
    iata STRING,
    name STRING,
    county STRING,
    state STRING
)

PARTITIONED BY(yearmonthday int)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','

LOCATION 's3://objective-data-lake/CURATED/DEPARTMENT_AERODROMO/PROJECT_445798_AIRLINE-VRA-AIR/AERODROMOS_ICAO_NAME/'
TBLPROPERTIES ('skip.header.line.count'='1')
